name: iecdt_eda
channels:
  - conda-forge
  - nodefaults
dependencies:
  - ipykernel
  - xarray
  - flox
  - pandas
  - numpy
  - matplotlib
  - seaborn
  - cartopy
  - cis
  - xesmf
  - scipy
  - dask
  - zarr
  - s3fs
  - gcsfs
  - python-graphviz
  - pyarrow
  - geodatasets
  - geopandas
  - moviepy
  - ffmpeg
  - pydub
  - healpy
  - astropy-healpix
  - satpy
  - uxarray
  - intake==0.7.0
  - intake-esm
  - intake-xarray==0.7.0
  - pip
  - pip:
    - xarray-regrid
